# Generated by Django 5.2.1 on 2025-05-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('N', 'Normal'), ('P', 'Preferencial')], max_length=1)),
                ('especialidade', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
