# Generated by Django 5.2.1 on 2025-05-30 23:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senha',
            name='chamado_para_guiche',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='senha',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
